#Dominios de Colisão
joao[0]=A
maria[0]=A

router[0]=A
router[1]=B

isp[0]=B
isp[1]=C
isp[2]=D

internet[0]=C

vps[0]=D

#Configurando ips
joao[exec]=ifconfig eth0 192.168.10.10/24
maria[exec]=ifconfig eth0 192.168.10.20/24

router[exec]=ifconfig eth0 192.168.10.1/24
router[exec]=ifconfig eth1 50.15.0.1/16

isp[exec]=ifconfig eth0 50.15.0.100/16
isp[exec]=ifconfig eth1 200.20.30.200/16
isp[exec]=ifconfig eth2 150.0.0.100/16

internet[exec]=ifconfig eth0 200.20.30.171/16

vps[exec]=ifconfig eth0 150.0.0.15/16

#Gateway
joao[exec]=route add default gw 192.168.10.1
maria[exec]=route add default gw 192.168.10.1

router[exec]=route add -net 150.0.0.0/16 gw 50.15.0.100
router[exec]=route add -net 200.20.0.0/16 gw 50.15.0.100
router[exec]=route add -net 192.168.10.0/24 gw 192.168.10.1

isp[exec]=route add -net 150.0.0.0/16 gw 150.0.0.100
isp[exec]=route add -net 200.20.0.0/16 gw 200.20.30.200
isp[exec]=route add -net 192.168.10.0/24 gw 50.15.0.1

vps[exec]=route add default gw 150.0.0.100

internet[exec]=route add default gw 200.20.30.200
