vrrp_instance VI_1 {
    state MASTER
    interface eth0              # Vlaned interface
    track_interface {           # Interface state we monitor
      eth0
      eth1
    }
    virtual_router_id 51
    priority 100
    virtual_ipaddress {
        192.168.1.1 
    }
    virtual_routes {
        default gw 50.1.1.2
    }
}



