clientelan[0]=A

interno[0]=A
interno[exec]=ifconfig eth0 192.168.1.1/24
interno[exec]=/etc/init.d/apache2 start
interno[exec]=/etc/init.d/ssh start
interno[exec]=route add default gw 192.168.1.2

router[0]=A
router[1]=B
router[exec]=ifconfig eth0 192.168.1.2/24
router[exec]=ifconfig eth1 50.0.0.1/30
router[exec]=/etc/init.d/ssh start
router[exec]=/etc/init.d/isc-dhcp-server restart
router[exec]=route add default gw 50.0.0.2
router[exec]=iptables -t nat -A PREROUTING -i eth1 -p tcp --dport 80 -j DNAT --to 192.168.1.1
router[exec]=iptables -t nat -A PREROUTING -i eth1 -p tcp --dport 443 -j DNAT --to 192.168.1.1
router[exec]=iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE
router[exec]=iptables -A INPUT -s 192.168.1.0/24 -j ACCEPT
router[exec]=iptables -A INPUT -i eth1 -p tcp --dport 22 -j DROP

isp[0]=B
isp[1]=C
isp[2]=D
isp[3]=E
isp[4]=F
isp[exec]=ifconfig eth0 50.0.0.2/30
isp[exec]=ifconfig eth1 150.1.2.1/28
isp[exec]=ifconfig eth2 60.70.80.91/28
isp[exec]=ifconfig eth3 200.0.0.101/28
isp[exec]=ifconfig eth4 8.8.8.9/28
isp[exec]=route add -net 192.168.1.0/24 gw 50.0.0.1
isp[exec]=route add -net 150.1.2.0/28 gw 150.1.2.3
isp[exec]=route add -net 60.70.80.0/28 gw 60.70.80.90
isp[exec]=route add -net 200.0.0.0/28 gw 200.0.0.100
isp[exec]=route add -net 8.8.8.0/28 gw 8.8.8.8
isp[exec]=iptables -A FORWARD -s 10.0.0.0/8 -j DROP
isp[exec]=iptables -A FORWARD -d 10.0.0.0/8 -j DROP
isp[exec]=iptables -A FORWARD -s 172.16.0.0/12 -j DROP
isp[exec]=iptables -A FORWARD -d 172.16.0.0/12 -j DROP
isp[exec]=iptables -A FORWARD -s 192.168.0.0/16 -j DROP
isp[exec]=iptables -A FORWARD -d 192.168.0.0/16 -j DROP

dnscombr[0]=C
dnscombr[exec]=ifconfig eth0 150.1.2.3/28
dnscombr[exec]=route add default gw 150.1.2.1
dnscombr[exec]=/etc/init.d/bind9 restart
dnscombr[exec]=cp /labdata/db.com.br /etc/bind/db.com.br
dnscombr[exec]=cp /labdata/named.conf.local /etc/bind/named.conf.local
dnscombr[exec]=/etc/init.d/bind restart

clienteinternet[0]=D
clienteinternet[exec]=ifconfig eth0 60.70.80.90/28
clienteinternet[exec]=route add default gw 60.70.80.91

commerce[0]=E
commerce[exec]=ifconfig eth0 200.0.0.100/28
commerce[exec]=/etc/init.d/apache2 start
commerce[exec]=/etc/init.d/ssh start
commerce[exec]=route add default gw 200.0.0.101

dnsbr[0]=F
dnsbr[exec]=ifconfig eth0 8.8.8.8/28
dnsbr[exec]=route add default gw 8.8.8.9
dnsbr[exec]=/etc/init.d/bind9 restart
dnsbr[exec]=cp /labdata/db.br /etc/bind/db.br
dnsbr[exec]=cp /labdata/named.conf.local /etc/bind/named.conf.local
dnsbr[exec]=/etc/init.d/bind restart

clientelan[exec]=dhclient eth0 -v
