router[0]=A
router[bridged]=true
#bridged faz um conteiner se conecta com uma interface real (docker0 172.17.0.1)
#o bridged faz o eth1 do router finar na mesma faixa, sendo assim ele e o (172.17.0.2)
router[exec]=ifconfig eth0 192.168.1.10/24
router[exec]=iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE
router[exec]=iptables -t nat -A PREROUTING -i eth1 -p tcp --dport 80 -j DNAT --to 192.168.1.11

c1[0]=A
c1[exec]=ifconfig eth0 192.168.1.11/24
c1[exec]=route add default gw 192.168.1.10
c1[exec]=/etc/init.d/apache2 start
