cliente[0]=A

sw[0]=A
sw[1]=B

sw[exec]=brctl addbr br0
sw[exec]=brctl addif br0 eth0 eth1
sw[exec]=ifconfig br0 up

router1[0]=B
router1[1]=C
router1[exec]=ifconfig eth0 192.168.0.1/24
router1[exec]=ifconfig eth1 200.100.50.1/29
router1[exec]=etc/init.d/isc-dhcp-server start
router1[exec]=route add -net 5.5.5.0/24 gw 200.100.50.2
router1[exec]=route add -net 6.6.6.0/24 gw 200.100.50.3
router1[exec]=route add -net 7.7.7.0/24 gw 200.100.50.4

swcore[0]=C
swcore[1]=D
swcore[2]=E
swcore[3]=F
swcore[exec]=brctl addbr br0
swcore[exec]=brctl addif br0 eth0 eth1 eth2 eth3
swcore[exec]=ifconfig br0 up

router2[0]=D
router2[1]=AA
router2[exec]=ifconfig eth0 200.100.50.2/29
router2[exec]=ifconfig eth1 5.5.5.5/24
router2[exec]=route add -net 192.168.0.0/24 gw 200.100.50.1
router2[exec]=route add -net 6.6.6.0/24 gw 200.100.50.3
router2[exec]=route add -net 7.7.7.0/24 gw 200.100.50.4


router3[0]=E
router3[1]=BB
router3[exec]=ifconfig eth0 200.100.50.3/29
router3[exec]=ifconfig eth1 6.6.6.6/24
router3[exec]=route add -net 192.168.0.0/24 gw 200.100.50.1
router3[exec]=route add -net 5.5.5.0/24 gw 200.100.50.2
router3[exec]=route add -net 7.7.7.0/24 gw 200.100.50.4

router4[0]=F
router4[1]=CC
router4[exec]=ifconfig eth0 200.100.50.4/29
router4[exec]=ifconfig eth1 7.7.7.7/24
router4[exec]=route add -net 192.168.0.0/24 gw 200.100.50.1
router4[exec]=route add -net 5.5.5.0/24 gw 200.100.50.2
router4[exec]=route add -net 6.6.6.0/24 gw 200.100.50.3

cliente[exec]=dhclient -v

