clientea[0]=A
clienteb[0]=A

serverweb[0]=B
serverweb[exec]=ifconfig eth0 192.168.100.1/24
serverweb[exec]=route add default gw 192.168.100.2

router[0]=A
router[1]=B
router[2]=C

isp[0]=C
isp[1]=D
isp[2]=E

clienteinternet[0]=D
clienteinternet[exec]=ifconfig eth0 60.70.80.90/24
clienteinternet[exec]=route add default gw 60.70.80.91

server[0]=E
server[exec]=ifconfig eth0 200.0.0.100/24
server[exec]=route add default gw 200.0.0.101


router[exec]=ifconfig eth0 192.168.1.1/24
router[exec]=ifconfig eth1 192.168.100.2/24
router[exec]=ifconfig eth2 50.0.0.1/30
router[exec]=/etc/init.d/isc-dhcp-server start
router[exec]=route add default gw 50.0.0.2

isp[exec]=ifconfig eth0 50.0.0.2/30
isp[exec]=ifconfig eth1 60.70.80.91/24
isp[exec]=ifconfig eth2 200.0.0.101/24
isp[exec]=route add -net 192.168.1.0/24 gw 50.0.0.1
isp[exec]=route add -net 192.168.100.0/24 gw 50.0.0.1
isp[exec]=route add -net 60.70.80.0/24 gw 60.70.80.90
isp[exec]=route add -net 200.0.0.100/24 gw 200.0.0.100



clientea[exec]=dhclient eth0 -v
clienteb[exec]=dhclient eth0 -v
