aluno[0]=A
lab[0]=A

router[0]=A
router[1]=B

internet[0]=B
internet[1]=C
internet[2]=D
internet[3]=E

vps[0]=C
site[0]=D
cliente[0]=E

aluno[exec]=ifconfig eth0 192.168.1.10/24
aluno[exec]=route add default gw 192.168.1.1

lab[exec]=ifconfig eth0 192.168.1.20/24
lab[exec]=route add default gw 192.168.1.1

router[exec]=ifconfig eth0 192.168.1.1/24
router[exec]=ifconfig eth1 200.10.20.30/24
router[exec]=route add -net 192.168.1.0/24 gw 192.168.1.1
router[exec]=route add -net 54.0.0.0/24 gw 200.10.20.31
router[exec]=route add -net 15.10.12.15/24 gw 200.10.20.31
router[exec]=route add -net 110.20.30.40/24 gw 200.10.20.31

internet[exec]=ifconfig eth0 200.10.20.31/24
internet[exec]=ifconfig eth1 54.0.0.16/24
internet[exec]=ifconfig eth2 15.10.12.16/24
internet[exec]=ifconfig eth3 110.20.30.41/24

internet[exec]=route add -net 192.168.1.0/24 gw 200.10.20.30
internet[exec]=route add -net 54.0.0.0/24 gw 54.0.0.15
internet[exec]=route add -net 15.10.12.0/24 gw 15.10.12.15
internet[exec]=route add -net 110.20.30.0/24 gw 110.20.30.40

vps[exec]=ifconfig eth0 54.0.0.15/24
vps[exec]=route add default gw 54.0.0.16

site[exec]=ifconfig eth0 15.10.12.15/24
site[exec]=route add default gw 15.10.12.16

cliente[exec]=ifconfig eth0 110.20.30.40/24
cliente[exec]=route add default gw 110.20.30.41
